artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: basemodel
  BASE_MODEL_NAME: VGG16_base_model.h5
  UPDATED_BASE_MODEL_NAME: updated_VGG16_base_model.h5
  CHECK_POINT_DIR: checkpoints
  BASR_LOG_DIR: base_model_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks


source_download_path: https://drive.google.com/drive/folders/1zWxSffR3WaSWPayXmBU57hJlaRIYSmF2?usp=sharing